[project]
name = "ml-deep-challanges"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "isort>=5.13.2",
    "numpy>=2.2.1",
    "pre-commit>=4.0.1",
    "ruff>=0.8.4",
]
